### ISSUE TITLE
tp - tpa 

### ISSUE THREAD

**Issue by Erz-spec** [1104mc/teleport-plugin#10]
Én ezt a teleport request dolgot egy kicsit máshogy gondoltam el. Ha játszottál MesterMC-vel akkor lehet ismerős a rendszer. Úgy volt, hogy beírtad, hogy /tpa + a player neve akire akire akarsz tpzni és akkor feljön az adott embernél az, hogy x ember rád akar teleportálni és akkor ott csak be kellett írni, hogy /tpaccept vagy /tpdeny, így működött. Nem volt egy rossz rendszer az sem, de annyi, hogy itt lehetne egy olyat csinálni mint a spectator parancsnál a vissza teleportálás lehetőség kiválasztásánál, hogy ott rá kell kattintani arra, hogy ahonnan indultam oda vissza akarok e tpzni. Ezt a kattintással elfogadós rendszert szerintem tök jó lenne behozni a tpa plugin rendszerbe is. De, hogy szegény bedrockosok is tudjanak tpazni így a /tpaccept jó lenne nekik. Ja és mivel nem volt nagyon rajtam kívül tesztalany így a dolog működését nem tudom igazolni mert a magamra tpzést nagyon nem észlelem szóval majd ha ketten fent leszünk akkor kipróbálhatjuk. És még az is fontos lenne, hogy a /tp parancsot csak admin és staff tudja csinálni és ne kérelem alapú legyen. Engem ez a tp - tpa dolog kicsit összezavart, elejinte nem értettem, hogy hogyan csináltad meg. De szólj ha valamit csináltál ezzel és akkor felnézek még egyszer.

**Comment by ProgrammerPeter2** [comment]
Ebben a rendszerben, a `/tp` parancs működik `/tpa`-ként és ha `/tp <player>`-ként használod akkor a menü nélkül is el tudsz küldeni direkt teleport kérelmet (lásd #4).
Egyébként az elfogadó üzenet egy jó ötlet, hamarosan azt is megcsinálom.

**Comment by ProgrammerPeter2** [comment]
Tehát a lefejlesztendő dolgok a következők:

- [ ] A `/tp` parancsot `/tpa`-ra kell átnevezni
- [ ] A `/tpa` parancsot `/tpaccept`-re kell átnevezni
- [ ] A `/tpaccept` parancs egy paraméterrel bővül: `accept` és `deny` - elfogadás, elutasítás
- [ ] A kérelem-üzenetbe vissza kell rakni az elfogadás/elutasítás gombokat, ammenyiben javas játékosról van szó
